title: AIISC Summer Camp
description: A website hosted by the Artificial Intelligence Institute of South Carolina
theme: just-the-docs
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "vendor"]

url: https://postybaloney.github.io/
baseurl: 'aiisc-summer-school/'

color_scheme: dark
search_enabled: false
heading_anchors: true
permalink: pretty

aux_links:
  Home: https://postybaloney.github.io/aiisc-summer-school/
  About: https://postybaloney.github.io/aiisc-summer-school/Pages/About/
  Schedule: https://postybaloney.github.io/aiisc-summer-school/Pages/Schedule/
  Gallery: https://postybaloney.github.io/aiisc-summer-school/Pages/Gallery/
  Testimonials: https://postybaloney.github.io/aiisc-summer-school/Pages/Testimonials
